name: 🚀 Deploy Soporteregio Blog

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v5

      - name: 🔐 Prepare SSH key
        shell: bash
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -p 2222 ${{ secrets.DEPLOY_SERVER }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
      
      - name: Build del sitio
        run: hugo --cleanDestinationDir
      
      - name: 🚀 Rsync Deploy to VPS
        shell: bash
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -p 2222 ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} bash -s <<'EOF'
            sudo mkdir -p /var/www/html/soporteregio.com/public_html/
            sudo chown -R $USER:www-data /var/www/html/soporteregio.com/public_html/
            sudo chmod -R 775 /var/www/html/soporteregio.com/public_html/
          EOF

          rsync -rlvz --delete \
            --no-perms --no-owner --no-group --omit-dir-times \
            -e "ssh -i ~/.ssh/deploy_key -p 2222 -o StrictHostKeyChecking=no" \
            public/ \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }}:/var/www/html/soporteregio.com/public_html/

          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -p 2222 ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} bash -s <<'EOF'
            ln -sfn /var/www/html/dokuwiki /var/www/html/soporteregio.com/public_html/wiki
            ln -sfn /usr/share/phpmyadmin /var/www/html/soporteregio.com/public_html/phpmyadmin
            sudo chown -R www-data:www-data /var/www/html/soporteregio.com/public_html/
            sudo chmod -R 755 /var/www/html/soporteregio.com/public_html/
          EOF
