name: 🚀 Deploy Soporteregio Blog

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v3

      - name: 🛠️ Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      
      - name: Build del sitio
        run: hugo --cleanDestinationDir
      
      - name: 🚀 Rsync Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -p 2222 ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} "
            echo '' | sudo -S chown -R rlopez:www-data /var/www/html/soporteregio.com/public_html/ &&
            echo '' | sudo -S chmod -R 775 /var/www/html/soporteregio.com/public_html/"
    
          rsync -avz -e "ssh -p 2222 -o StrictHostKeyChecking=no" --delete public/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }}:/var/www/html/soporteregio.com/public_html/
    
          ssh -o StrictHostKeyChecking=no -p 2222 ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} "
            echo '' | sudo -S chown -R www-data:www-data /var/www/html/soporteregio.com/public_html/ &&
            echo '' | sudo -S chmod -R 755 /var/www/html/soporteregio.com/public_html/ &&
            cd /var/www/html/soporteregio.com/public_html &&
            echo '' | sudo -S /usr/bin/ln -sfn /var/www/html/dokuwiki /var/www/html/soporteregio.com/public_html/wiki &&
            echo '' | sudo -S /usr/bin/ln -sfn /usr/share/phpmyadmin /var/www/html/soporteregio.com/public_html/phpmyadmin
          "